import type { CertificateLayoutConfig } from "../documents/certificate-layout.types.js";

/** Landscape membership ID card (matches Front/back page.jpg aspect 1296×816). */
export const MEMBERSHIP_ID_PAGE_WIDTH = 648;
export const MEMBERSHIP_ID_PAGE_HEIGHT = 408;

export const MEMBERSHIP_ID_CERT_TEMPLATE_CODE = "MEMBERSHIP_ID_CERT_V1";

/**
 * Default field positions for the official ORIASC membership ID card.
 * Coordinates are PDF points on a 648×408 page (0.5× the 1296×816 px artwork).
 * Refine in Documents → Templates → Design after seeding.
 */
export const DEFAULT_MEMBERSHIP_ID_CERTIFICATE_LAYOUT: CertificateLayoutConfig = {
  version: 1,
  pageWidth: MEMBERSHIP_ID_PAGE_WIDTH,
  pageHeight: MEMBERSHIP_ID_PAGE_HEIGHT,
  fields: [],
  pages: [
    {
      key: "front",
      label: "Front",
      sourceFileUrl: "/uploads/document-template-sources/membership-id-front-v1.jpg",
      fields: [
        {
          key: "photo",
          label: "Photo",
          type: "image",
          x: 28,
          y: 118,
          width: 118,
          height: 140,
        },
        {
          key: "certificateId",
          label: "Lakk ID",
          type: "text",
          x: 430,
          y: 88,
          width: 180,
          height: 18,
          fontSize: 10,
          fontWeight: "bold",
          align: "left",
          color: "#111827",
        },
        {
          key: "fullName",
          label: "Full name",
          type: "text",
          x: 250,
          y: 130,
          width: 360,
          height: 20,
          fontSize: 12,
          fontWeight: "bold",
          align: "left",
          color: "#111827",
        },
        {
          key: "position",
          label: "Position",
          type: "text",
          x: 250,
          y: 168,
          width: 360,
          height: 18,
          fontSize: 11,
          align: "left",
          color: "#111827",
        },
        {
          key: "membershipRole",
          label: "Membership role",
          type: "text",
          x: 250,
          y: 206,
          width: 360,
          height: 18,
          fontSize: 11,
          align: "left",
          color: "#111827",
        },
        {
          key: "phone",
          label: "Phone number",
          type: "text",
          x: 250,
          y: 244,
          width: 360,
          height: 18,
          fontSize: 11,
          align: "left",
          color: "#111827",
        },
      ],
    },
    {
      key: "back",
      label: "Back",
      sourceFileUrl: "/uploads/document-template-sources/membership-id-back-v1.jpg",
      fields: [
        {
          key: "issuedAt",
          label: "Issued date",
          type: "date",
          x: 150,
          y: 118,
          width: 140,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "expiresAt",
          label: "Expiry date",
          type: "date",
          x: 420,
          y: 118,
          width: 140,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "zone",
          label: "Zone / City",
          type: "text",
          x: 200,
          y: 168,
          width: 380,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "cityDistrict",
          label: "City / District",
          type: "text",
          x: 160,
          y: 196,
          width: 400,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "kebele",
          label: "Kebele",
          type: "text",
          x: 140,
          y: 224,
          width: 420,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "mosque",
          label: "Mosque",
          type: "text",
          x: 160,
          y: 252,
          width: 400,
          height: 16,
          fontSize: 10,
          align: "left",
          color: "#111827",
        },
        {
          key: "signature",
          label: "Signature",
          type: "image",
          x: 380,
          y: 300,
          width: 140,
          height: 40,
        },
        {
          key: "seal",
          label: "Stamp",
          type: "image",
          x: 540,
          y: 290,
          width: 70,
          height: 70,
        },
      ],
    },
  ],
};
