import type { CertificateLayoutConfig } from "../documents/certificate-layout.types.js";

/** US Letter in PDF points (matches the official Halal certificate PDF backgrounds). */
export const HALAL_CERT_PAGE_WIDTH = 612;
export const HALAL_CERT_PAGE_HEIGHT = 792;

export const HALAL_BUSINESS_CERT_TEMPLATE_CODE = "HALAL_BUSINESS_CERT_V1";
export const HALAL_PRODUCT_CERT_TEMPLATE_CODE = "HALAL_PRODUCT_CERT_V1";

/**
 * Default field positions for `halal-business-certificate.pdf` (company / slaughter approval form).
 * Coordinates are PDF points from the top-left of a US Letter page (612×792).
 * Refine in Documents → Certificate designer after seeding if needed.
 */
export const DEFAULT_HALAL_BUSINESS_CERTIFICATE_LAYOUT: CertificateLayoutConfig = {
  version: 1,
  pageWidth: HALAL_CERT_PAGE_WIDTH,
  pageHeight: HALAL_CERT_PAGE_HEIGHT,
  fields: [
    {
      key: "certificateId",
      label: "Reg. No.",
      type: "text",
      x: 380,
      y: 148,
      width: 170,
      height: 16,
      fontSize: 10,
      fontWeight: "bold",
      align: "left",
      color: "#111827",
    },
    {
      key: "businessName",
      label: "Entity name",
      type: "text",
      x: 250,
      y: 248,
      width: 300,
      height: 18,
      fontSize: 11,
      fontWeight: "bold",
      align: "left",
      color: "#14532d",
    },
    {
      key: "category",
      label: "Product type",
      type: "text",
      x: 185,
      y: 308,
      width: 340,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "issuedAt",
      label: "Issued on",
      type: "date",
      x: 115,
      y: 528,
      width: 140,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "expiresAt",
      label: "Valid until",
      type: "date",
      x: 380,
      y: 528,
      width: 140,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "signature",
      label: "Signature",
      type: "image",
      x: 70,
      y: 460,
      width: 120,
      height: 48,
    },
    {
      key: "seal",
      label: "Seal",
      type: "image",
      x: 420,
      y: 450,
      width: 90,
      height: 90,
    },
    {
      key: "qrCode",
      label: "Verification QR",
      type: "qrcode",
      x: 40,
      y: 650,
      width: 72,
      height: 72,
    },
  ],
};

/**
 * Default field positions for `halal-product-certificate.pdf` (consignment / slaughtering form).
 * Coordinates are PDF points from the top-left of a US Letter page (612×792).
 */
export const DEFAULT_HALAL_PRODUCT_CERTIFICATE_LAYOUT: CertificateLayoutConfig = {
  version: 1,
  pageWidth: HALAL_CERT_PAGE_WIDTH,
  pageHeight: HALAL_CERT_PAGE_HEIGHT,
  fields: [
    {
      key: "certificateNumber",
      label: "No.",
      type: "text",
      x: 430,
      y: 138,
      width: 130,
      height: 16,
      fontSize: 10,
      fontWeight: "bold",
      align: "left",
      color: "#111827",
    },
    {
      key: "issuedAt",
      label: "Date",
      type: "date",
      x: 430,
      y: 158,
      width: 130,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "consignmentPcs",
      label: "Consignment details (PCS)",
      type: "text",
      x: 200,
      y: 278,
      width: 280,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "netWeightKg",
      label: "Net weight (kg)",
      type: "text",
      x: 175,
      y: 298,
      width: 200,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "grossWeightKg",
      label: "Gross weight (kg)",
      type: "text",
      x: 185,
      y: 318,
      width: 200,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "shipping",
      label: "Shipping",
      type: "text",
      x: 160,
      y: 338,
      width: 280,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "voyageFlightNo",
      label: "Voyage / flight no.",
      type: "text",
      x: 200,
      y: 358,
      width: 240,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "loadingPort",
      label: "Loading port",
      type: "text",
      x: 185,
      y: 378,
      width: 280,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "destination",
      label: "Destination",
      type: "text",
      x: 175,
      y: 398,
      width: 300,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "slaughteringDate",
      label: "Slaughtering date",
      type: "date",
      x: 205,
      y: 418,
      width: 180,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "productionDate",
      label: "Production date",
      type: "date",
      x: 200,
      y: 438,
      width: 180,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "expiryDate",
      label: "Expiry date",
      type: "date",
      x: 170,
      y: 458,
      width: 180,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "healthCertificateNo",
      label: "Health certificate no.",
      type: "text",
      x: 220,
      y: 478,
      width: 240,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "slaughteringCertificate",
      label: "Slaughtering certificate",
      type: "text",
      x: 230,
      y: 498,
      width: 240,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "signature",
      label: "Signature",
      type: "image",
      x: 150,
      y: 518,
      width: 140,
      height: 40,
    },
    {
      key: "authorizedRepresentative",
      label: "Authorized representative",
      type: "text",
      x: 230,
      y: 558,
      width: 260,
      height: 16,
      fontSize: 10,
      align: "left",
      color: "#111827",
    },
    {
      key: "seal",
      label: "Seal",
      type: "image",
      x: 460,
      y: 520,
      width: 80,
      height: 80,
    },
    {
      key: "qrCode",
      label: "Verification QR",
      type: "qrcode",
      x: 40,
      y: 650,
      width: 72,
      height: 72,
    },
  ],
};
