import React, { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import {
  History,
  Search,
  Filter,
  Download,
  Calendar,
  User,
  FileText,
  RefreshCw,
} from "lucide-react";
import {
  getReportAuditLogs,
  getModuleLabel,
  getReportTypeLabel,
} from "@/services/reports";
import { toast } from "sonner";
import { format } from "date-fns";

export default function ReportAuditLog() {
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);
  const [totalPages, setTotalPages] = useState(0);

  // Filters
  const [moduleFilter, setModuleFilter] = useState<string>("all");
  const [generatedByFilter, setGeneratedByFilter] = useState<string>("");
  const [startDateFilter, setStartDateFilter] = useState<string>("");
  const [endDateFilter, setEndDateFilter] = useState<string>("");

  useEffect(() => {
    loadLogs();
  }, [page, pageSize, moduleFilter, generatedByFilter, startDateFilter, endDateFilter]);

  const loadLogs = async () => {
    try {
      setLoading(true);
      const params: any = {
        page,
        pageSize,
      };

      if (moduleFilter !== "all") {
        params.module = moduleFilter;
      }
      if (generatedByFilter) {
        params.generatedBy = generatedByFilter;
      }
      if (startDateFilter) {
        params.startDate = startDateFilter;
      }
      if (endDateFilter) {
        params.endDate = endDateFilter;
      }

      const response = await getReportAuditLogs(params);
      setLogs(response.items);
      setTotal(response.total);
      setTotalPages(response.totalPages);
    } catch (error: any) {
      console.error("Failed to load audit logs:", error);
      toast.error("Failed to load audit logs");
    } finally {
      setLoading(false);
    }
  };

  const handleClearFilters = () => {
    setModuleFilter("all");
    setGeneratedByFilter("");
    setStartDateFilter("");
    setEndDateFilter("");
    setPage(1);
  };

  const handleExport = () => {
    // Export audit logs to CSV
    const csvRows = [
      ["Generated At", "Module", "Report Type", "Generated By", "Export Format", "Filters"].join(","),
      ...logs.map((log) =>
        [
          log.generatedAt,
          log.module,
          log.reportType,
          log.generatedByUser
            ? `${log.generatedByUser.firstName} ${log.generatedByUser.lastName}`
            : log.generatedBy,
          log.exportFormat || "-",
          JSON.stringify(log.filters || {}),
        ].join(",")
      ),
    ];

    const csv = csvRows.join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `report-audit-logs-${new Date().toISOString()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    toast.success("Audit logs exported");
  };

  const MODULES = [
    "EMPLOYEES",
    "DEPARTMENTS",
    "LEAVES",
    "ATTENDANCE",
    "PAYROLL",
    "TASKS",
    "ASSETS",
    "EXPENSES",
    "DOCUMENTS",
    "TIMESHEETS",
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Report Audit Log</h2>
          <p className="text-muted-foreground">
            Track who generated and exported reports
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={loadLogs}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
          <Button variant="outline" onClick={handleExport}>
            <Download className="mr-2 h-4 w-4" />
            Export
          </Button>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Filter className="h-5 w-5" />
            Filters
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <Label>Module</Label>
              <Select value={moduleFilter} onValueChange={setModuleFilter}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Modules</SelectItem>
                  {MODULES.map((mod) => (
                    <SelectItem key={mod} value={mod}>
                      {getModuleLabel(mod)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Generated By</Label>
              <Input
                placeholder="User ID or email"
                value={generatedByFilter}
                onChange={(e) => setGeneratedByFilter(e.target.value)}
              />
            </div>
            <div>
              <Label>Start Date</Label>
              <Input
                type="date"
                value={startDateFilter}
                onChange={(e) => setStartDateFilter(e.target.value)}
              />
            </div>
            <div>
              <Label>End Date</Label>
              <Input
                type="date"
                value={endDateFilter}
                onChange={(e) => setEndDateFilter(e.target.value)}
              />
            </div>
          </div>
          <div className="flex justify-end mt-4">
            <Button variant="outline" onClick={handleClearFilters}>
              Clear Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Audit Logs Table */}
      <Card>
        <CardHeader>
          <CardTitle>Audit Logs</CardTitle>
          <CardDescription>
            {total} total log entries
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : logs.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12">
              <History className="h-12 w-12 text-muted-foreground mb-4" />
              <p className="text-muted-foreground">No audit logs found</p>
            </div>
          ) : (
            <>
              <div className="border rounded-lg overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Generated At</TableHead>
                      <TableHead>Module</TableHead>
                      <TableHead>Report Type</TableHead>
                      <TableHead>Generated By</TableHead>
                      <TableHead>Export Format</TableHead>
                      <TableHead>Template</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {logs.map((log) => (
                      <TableRow key={log.id}>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Calendar className="h-4 w-4 text-muted-foreground" />
                            {format(new Date(log.generatedAt), "MMM dd, yyyy HH:mm")}
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">
                            {getModuleLabel(log.module)}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Badge variant="secondary">
                            {getReportTypeLabel(log.reportType)}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {log.generatedByUser ? (
                            <div className="flex items-center gap-2">
                              <User className="h-4 w-4 text-muted-foreground" />
                              <div>
                                <p className="text-sm font-medium">
                                  {log.generatedByUser.firstName}{" "}
                                  {log.generatedByUser.lastName}
                                </p>
                                <p className="text-xs text-muted-foreground">
                                  {log.generatedByUser.email}
                                </p>
                              </div>
                            </div>
                          ) : (
                            <span className="text-sm text-muted-foreground">
                              {log.generatedBy || "Unknown"}
                            </span>
                          )}
                        </TableCell>
                        <TableCell>
                          {log.exportFormat ? (
                            <Badge variant="outline">{log.exportFormat}</Badge>
                          ) : (
                            <span className="text-sm text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {log.templateId ? (
                            <Badge variant="secondary">
                              <FileText className="mr-1 h-3 w-3" />
                              Template
                            </Badge>
                          ) : (
                            <span className="text-sm text-muted-foreground">Custom</span>
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>

              {/* Pagination */}
              {totalPages > 1 && (
                <div className="flex items-center justify-between mt-4">
                  <div className="flex items-center gap-2">
                    <Label>Rows per page:</Label>
                    <Select
                      value={String(pageSize)}
                      onValueChange={(v) => {
                        setPageSize(Number(v));
                        setPage(1);
                      }}
                    >
                      <SelectTrigger className="w-24">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="10">10</SelectItem>
                        <SelectItem value="20">20</SelectItem>
                        <SelectItem value="50">50</SelectItem>
                        <SelectItem value="100">100</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPage((p) => Math.max(1, p - 1))}
                      disabled={page === 1}
                    >
                      Previous
                    </Button>
                    <span className="text-sm">
                      Page {page} of {totalPages}
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                      disabled={page === totalPages}
                    >
                      Next
                    </Button>
                  </div>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

